<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>pset4_template</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="pset4_template_files/libs/clipboard/clipboard.min.js"></script>
<script src="pset4_template_files/libs/quarto-html/quarto.js"></script>
<script src="pset4_template_files/libs/quarto-html/popper.min.js"></script>
<script src="pset4_template_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="pset4_template_files/libs/quarto-html/anchor.min.js"></script>
<link href="pset4_template_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="pset4_template_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="pset4_template_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="pset4_template_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="pset4_template_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<hr>
<hr>
<p><strong>PS4:</strong> Due Sat Nov 2 at 5:00PM Central. Worth 100 points. We use (<code>*</code>) to indicate a problem that we think might be time consuming.</p>
<section id="style-points-10-pts" class="level2">
<h2 class="anchored" data-anchor-id="style-points-10-pts">Style Points (10 pts)</h2>
<p>Please refer to the minilesson on code style <strong><a href="https://uchicago.zoom.us/rec/share/pG_wQ-pHTQrJTmqNn4rcrw5V194M2H2s-2jdy8oVhWHkd_yZt9o162IWurpA-fxU.BIQlSgZLRYctvzp-">here</a></strong>.</p>
</section>
<section id="submission-steps-10-pts" class="level2">
<h2 class="anchored" data-anchor-id="submission-steps-10-pts">Submission Steps (10 pts)</h2>
<ol type="1">
<li>This problem set is a paired problem set.</li>
<li>Play paper, scissors, rock to determine who goes first. Call that person <em>Partner 1</em>.
<ul>
<li>Partner 1 (Attaullah Abbasi and attaullahabbasi):</li>
<li>Partner 2 (N/A - assignment completed solo):</li>
</ul></li>
<li>Partner 1 will accept the <code>ps4</code> and then share the link it creates with their partner. You can only share it with one partner so you will not be able to change it after your partner has accepted.</li>
<li>“This submission is our work alone and complies with the 30538 integrity policy.” Add your initials to indicate your agreement: AA</li>
<li>“I have uploaded the names of anyone else other than my partner and I worked with on the problem set <strong><a href="https://docs.google.com/forms/d/185usrCREQaUbvAXpWhChkjghdGgmAZXA3lPWpXLLsts/edit">here</a></strong>” (1 point): AA</li>
<li>Late coins used this pset: 1 Late coins left after submission: 1</li>
<li>Knit your <code>ps4.qmd</code> to an PDF file to make <code>ps4.pdf</code>,
<ul>
<li>The PDF should not be more than 25 pages. Use <code>head()</code> and re-size figures when appropriate.</li>
</ul></li>
<li>(Partner 1): push <code>ps4.qmd</code> and <code>ps4.pdf</code> to your github repo.</li>
<li>(Partner 1): submit <code>ps4.pdf</code> via Gradescope. Add your partner on Gradescope.</li>
<li>(Partner 1): tag your submission in Gradescope</li>
</ol>
<p><strong>Important:</strong> Repositories are for tracking code. <strong>Do not commit the data or shapefiles to your repo.</strong> The best way to do this is with <code>.gitignore</code>, which we have covered in class. If you do accidentally commit the data, Github has a <a href="https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#removing-files-from-a-repositorys-history">guide</a>. The best course of action depends on whether you have pushed yet. This also means that both partners will have to download the initial raw data and any data cleaning code will need to be re-run on both partners’ computers.</p>
</section>
<section id="download-and-explore-the-provider-of-services-pos-file-10-pts" class="level2">
<h2 class="anchored" data-anchor-id="download-and-explore-the-provider-of-services-pos-file-10-pts">Download and explore the Provider of Services (POS) file (10 pts)</h2>
<ol type="1">
<li><p>For the 2016 data, I pulled the following variables:</p>
<ol type="i">
<li><code>PRVDR_NUM</code>: Unique CMS certification number for each hospital</li>
<li><code>FAC_NAME</code>: Facility name</li>
<li><code>PRVDR_CTGRY_CD</code>: Provider category, to identify hospitals</li>
<li><code>PRVDR_CTGRY_SBTYP_CD</code>: Provider subtype, to identify short-term hospitals</li>
<li><code>CRTFCTN_DT</code>: Certification date, to verify active facilities</li>
<li><code>ORGNL_PRTCPTN_DT</code>: Original participation date, to confirm participation history</li>
<li><code>PGM_TRMNTN_CD</code>: Termination code, to track closures</li>
<li><code>TRMNTN_EXPRTN_DT</code>: Termination date, to identify closure timelines</li>
<li><code>ZIP_CD</code>: Zip code for geographic analysis</li>
<li><code>STATE_CD</code>: State abbreviation, useful for filtering Texas and nearby states</li>
<li><code>CITY_NAME</code>: City name for additional geographic context</li>
<li><code>ST_ADR</code>: Street address for potential geolocation</li>
<li><code>CBSA_URBN_RRL_IND</code>: Urban-rural indicator, helpful for understanding location context</li>
<li><code>GNRL_CNTL_TYPE_CD</code>: Control type, to analyze hospital ownership</li>
</ol></li>
</ol>
<p>These variables allow for filtering, spatial analysis, tracking closures, and understanding hospital characteristics as required by the problem set.</p>
<ol start="2" type="1">
<li></li>
</ol>
<div id="946a7e4f" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the pos2016.csv file</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>data_2016 <span class="op">=</span> pd.read_csv(<span class="st">"pos2016.csv"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for short-term hospitals with provider type code 01 and subtype code 01</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>short_term_hospitals_2016 <span class="op">=</span> data_2016[(data_2016[<span class="st">'PRVDR_CTGRY_CD'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (data_2016[<span class="st">'PRVDR_CTGRY_SBTYP_CD'</span>] <span class="op">==</span> <span class="dv">1</span>)]</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># a. Count the number of hospitals in this subset</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>hospital_count_2016 <span class="op">=</span> short_term_hospitals_2016.shape[<span class="dv">0</span>]</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>hospital_count_2016</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>7245</code></pre>
</div>
</div>
<pre><code>a.</code></pre>
<p>The dataset reports 7,245 short-term hospitals for 2016.</p>
<p>This count seems high compared to typical figures from industry sources, such as the American Hospital Association (AHA), which might suggest differences in data scope or classification criteria used by CMS.</p>
<pre><code>b.</code></pre>
<p>According to the American Hospital Association (AHA), there were approximately 5,534 registered hospitals in the U.S. in 2016, with around 4,840 classified as community hospitals, which includes most short-term general hospitals. This figure is notably lower than the 7,245 short-term hospitals reported in the CMS dataset.</p>
<p>Reasons for the Discrepancy:</p>
<p>Data Scope: The CMS dataset may include facilities that are Medicare/Medicaid-certified but not registered with the AHA, potentially increasing the count.</p>
<p>Different Definitions: CMS may classify certain specialty hospitals or facilities providing limited services as short-term if they meet Medicare eligibility criteria, even if other sources don’t typically include them.</p>
<p>Timing and Updates: The dataset represents a Q4 2016 snapshot, while the AHA’s data may reflect closures, mergers, or reclassifications over the entire year.</p>
<p>These factors could explain the higher count of short-term hospitals in the CMS dataset compared to other industry sources.</p>
<ol start="3" type="1">
<li></li>
</ol>
<div id="6df19b80" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> altair <span class="im">as</span> alt</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load each year's data with appropriate encoding where needed</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>data_2016 <span class="op">=</span> pd.read_csv(<span class="st">"pos2016.csv"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>data_2017 <span class="op">=</span> pd.read_csv(<span class="st">"pos2017.csv"</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>data_2018 <span class="op">=</span> pd.read_csv(<span class="st">"pos2018.csv"</span>, encoding<span class="op">=</span><span class="st">"ISO-8859-1"</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>data_2019 <span class="op">=</span> pd.read_csv(<span class="st">"pos2019.csv"</span>, encoding<span class="op">=</span><span class="st">"ISO-8859-1"</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a function to filter for short-term hospitals</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> filter_short_term(data):</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> data[(data[<span class="st">'PRVDR_CTGRY_CD'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (data[<span class="st">'PRVDR_CTGRY_SBTYP_CD'</span>] <span class="op">==</span> <span class="dv">1</span>)]</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply filtering to each dataset and add a 'Year' column for each</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>data_2016 <span class="op">=</span> filter_short_term(data_2016)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>data_2016[<span class="st">'Year'</span>] <span class="op">=</span> <span class="dv">2016</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>data_2017 <span class="op">=</span> filter_short_term(data_2017)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>data_2017[<span class="st">'Year'</span>] <span class="op">=</span> <span class="dv">2017</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>data_2018 <span class="op">=</span> filter_short_term(data_2018)</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>data_2018[<span class="st">'Year'</span>] <span class="op">=</span> <span class="dv">2018</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>data_2019 <span class="op">=</span> filter_short_term(data_2019)</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>data_2019[<span class="st">'Year'</span>] <span class="op">=</span> <span class="dv">2019</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine all datasets into a single DataFrame</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>all_years_data <span class="op">=</span> pd.concat([data_2016, data_2017, data_2018, data_2019])</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Count the number of observations (hospitals) by year</span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>observations_by_year <span class="op">=</span> all_years_data.groupby(<span class="st">'Year'</span>).size().reset_index(name<span class="op">=</span><span class="st">'Count'</span>)</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot using Altair</span></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> alt.Chart(observations_by_year).mark_bar(color<span class="op">=</span><span class="st">'steelblue'</span>).encode(</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>alt.X(<span class="st">'Year:O'</span>, title<span class="op">=</span><span class="st">'Year'</span>),</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span>alt.Y(<span class="st">'Count:Q'</span>, title<span class="op">=</span><span class="st">'Number of Short-Term Hospitals'</span>)</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>).properties(</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="st">'Number of Observations in Dataset by Year'</span>,</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>    width<span class="op">=</span><span class="dv">400</span>,</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>    height<span class="op">=</span><span class="dv">300</span></span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Add text labels on top of each bar</span></span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>text <span class="op">=</span> bars.mark_text(</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>    align<span class="op">=</span><span class="st">'center'</span>,</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>    baseline<span class="op">=</span><span class="st">'bottom'</span>,</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>    dy<span class="op">=-</span><span class="dv">5</span>  <span class="co"># Adjust the position of the text above the bars</span></span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>).encode(</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>    text<span class="op">=</span><span class="st">'Count:Q'</span></span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine the bars and the text</span></span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a>(bars <span class="op">+</span> text).display()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/sd/jd56rfvs19gbncmb5yqlmfym0000gn/T/ipykernel_59453/949909169.py:7: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  data_2018 = pd.read_csv("pos2018.csv", encoding="ISO-8859-1")</code></pre>
</div>
<div class="cell-output cell-output-display">

<style>
  #altair-viz-f7b855e4acb84c8cada0e4856a245a9e.vega-embed {
    width: 100%;
    display: flex;
  }

  #altair-viz-f7b855e4acb84c8cada0e4856a245a9e.vega-embed details,
  #altair-viz-f7b855e4acb84c8cada0e4856a245a9e.vega-embed details summary {
    position: relative;
  }
</style>
<div id="altair-viz-f7b855e4acb84c8cada0e4856a245a9e"></div>
<script type="text/javascript">
  var VEGA_DEBUG = (typeof VEGA_DEBUG == "undefined") ? {} : VEGA_DEBUG;
  (function(spec, embedOpt){
    let outputDiv = document.currentScript.previousElementSibling;
    if (outputDiv.id !== "altair-viz-f7b855e4acb84c8cada0e4856a245a9e") {
      outputDiv = document.getElementById("altair-viz-f7b855e4acb84c8cada0e4856a245a9e");
    }
    const paths = {
      "vega": "https://cdn.jsdelivr.net/npm/vega@5?noext",
      "vega-lib": "https://cdn.jsdelivr.net/npm/vega-lib?noext",
      "vega-lite": "https://cdn.jsdelivr.net/npm/vega-lite@5.20.1?noext",
      "vega-embed": "https://cdn.jsdelivr.net/npm/vega-embed@6?noext",
    };

    function maybeLoadScript(lib, version) {
      var key = `${lib.replace("-", "")}_version`;
      return (VEGA_DEBUG[key] == version) ?
        Promise.resolve(paths[lib]) :
        new Promise(function(resolve, reject) {
          var s = document.createElement('script');
          document.getElementsByTagName("head")[0].appendChild(s);
          s.async = true;
          s.onload = () => {
            VEGA_DEBUG[key] = version;
            return resolve(paths[lib]);
          };
          s.onerror = () => reject(`Error loading script: ${paths[lib]}`);
          s.src = paths[lib];
        });
    }

    function showError(err) {
      outputDiv.innerHTML = `<div class="error" style="color:red;">${err}</div>`;
      throw err;
    }

    function displayChart(vegaEmbed) {
      vegaEmbed(outputDiv, spec, embedOpt)
        .catch(err => showError(`Javascript Error: ${err.message}<br>This usually means there's a typo in your chart specification. See the javascript console for the full traceback.`));
    }

    if(typeof define === "function" && define.amd) {
      requirejs.config({paths});
      require(["vega-embed"], displayChart, err => showError(`Error loading script: ${err.message}`));
    } else {
      maybeLoadScript("vega", "5")
        .then(() => maybeLoadScript("vega-lite", "5.20.1"))
        .then(() => maybeLoadScript("vega-embed", "6"))
        .catch(showError)
        .then(() => displayChart(vegaEmbed));
    }
  })({"config": {"view": {"continuousWidth": 300, "continuousHeight": 300}}, "layer": [{"mark": {"type": "bar", "color": "steelblue"}, "encoding": {"x": {"field": "Year", "title": "Year", "type": "ordinal"}, "y": {"field": "Count", "title": "Number of Short-Term Hospitals", "type": "quantitative"}}, "title": "Number of Observations in Dataset by Year"}, {"mark": {"type": "text", "align": "center", "baseline": "bottom", "dy": -5}, "encoding": {"text": {"field": "Count", "type": "quantitative"}, "x": {"field": "Year", "title": "Year", "type": "ordinal"}, "y": {"field": "Count", "title": "Number of Short-Term Hospitals", "type": "quantitative"}}, "title": "Number of Observations in Dataset by Year"}], "data": {"name": "data-3035dfcddf50b7a1f0c4777bb69a2f94"}, "height": 300, "width": 400, "$schema": "https://vega.github.io/schema/vega-lite/v5.20.1.json", "datasets": {"data-3035dfcddf50b7a1f0c4777bb69a2f94": [{"Year": 2016, "Count": 7245}, {"Year": 2017, "Count": 7260}, {"Year": 2018, "Count": 7277}, {"Year": 2019, "Count": 7303}]}}, {"mode": "vega-lite"});
</script>
</div>
</div>
<ol start="4" type="1">
<li><ol type="a">
<li></li>
</ol></li>
</ol>
<div id="533397f7" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> altair <span class="im">as</span> alt</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming data for each year is already filtered and loaded</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># If not, make sure data_2016, data_2017, data_2018, data_2019 are loaded and filtered as before</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a 'Year' column to each dataset</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>data_2016[<span class="st">'Year'</span>] <span class="op">=</span> <span class="dv">2016</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>data_2017[<span class="st">'Year'</span>] <span class="op">=</span> <span class="dv">2017</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>data_2018[<span class="st">'Year'</span>] <span class="op">=</span> <span class="dv">2018</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>data_2019[<span class="st">'Year'</span>] <span class="op">=</span> <span class="dv">2019</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine all datasets into a single DataFrame</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>all_years_data <span class="op">=</span> pd.concat([data_2016, data_2017, data_2018, data_2019])</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Count unique hospitals (by PRVDR_NUM) per year</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>unique_hospitals_by_year <span class="op">=</span> all_years_data.groupby(<span class="st">'Year'</span>)[<span class="st">'PRVDR_NUM'</span>].nunique().reset_index(name<span class="op">=</span><span class="st">'UniqueCount'</span>)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot using Altair</span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> alt.Chart(unique_hospitals_by_year).mark_bar(color<span class="op">=</span><span class="st">'seagreen'</span>).encode(</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>alt.X(<span class="st">'Year:O'</span>, title<span class="op">=</span><span class="st">'Year'</span>),</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span>alt.Y(<span class="st">'UniqueCount:Q'</span>, title<span class="op">=</span><span class="st">'Number of Unique Short-Term Hospitals'</span>)</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>).properties(</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="st">'Number of Unique Short-Term Hospitals in Dataset by Year'</span>,</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>    width<span class="op">=</span><span class="dv">400</span>,</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>    height<span class="op">=</span><span class="dv">300</span></span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Add text labels on top of each bar</span></span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>text <span class="op">=</span> bars.mark_text(</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>    align<span class="op">=</span><span class="st">'center'</span>,</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>    baseline<span class="op">=</span><span class="st">'bottom'</span>,</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>    dy<span class="op">=-</span><span class="dv">5</span>  <span class="co"># Adjust the position of the text above the bars</span></span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>).encode(</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>    text<span class="op">=</span><span class="st">'UniqueCount:Q'</span></span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the combined chart with bars and labels</span></span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>(bars <span class="op">+</span> text).display()</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a><span class="co"># Double checking for duplicates</span></span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for duplicates in PRVDR_NUM within each year</span></span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a>duplicates_2016 <span class="op">=</span> data_2016.duplicated(subset<span class="op">=</span><span class="st">'PRVDR_NUM'</span>).<span class="bu">sum</span>()</span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a>duplicates_2017 <span class="op">=</span> data_2017.duplicated(subset<span class="op">=</span><span class="st">'PRVDR_NUM'</span>).<span class="bu">sum</span>()</span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a>duplicates_2018 <span class="op">=</span> data_2018.duplicated(subset<span class="op">=</span><span class="st">'PRVDR_NUM'</span>).<span class="bu">sum</span>()</span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a>duplicates_2019 <span class="op">=</span> data_2019.duplicated(subset<span class="op">=</span><span class="st">'PRVDR_NUM'</span>).<span class="bu">sum</span>()</span>
<span id="cb7-48"><a href="#cb7-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-49"><a href="#cb7-49" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"2016 Duplicates: </span><span class="sc">{</span>duplicates_2016<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb7-50"><a href="#cb7-50" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"2017 Duplicates: </span><span class="sc">{</span>duplicates_2017<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb7-51"><a href="#cb7-51" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"2018 Duplicates: </span><span class="sc">{</span>duplicates_2018<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb7-52"><a href="#cb7-52" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"2019 Duplicates: </span><span class="sc">{</span>duplicates_2019<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">

<style>
  #altair-viz-68067fa3f2094a61bdc29adf78a4e555.vega-embed {
    width: 100%;
    display: flex;
  }

  #altair-viz-68067fa3f2094a61bdc29adf78a4e555.vega-embed details,
  #altair-viz-68067fa3f2094a61bdc29adf78a4e555.vega-embed details summary {
    position: relative;
  }
</style>
<div id="altair-viz-68067fa3f2094a61bdc29adf78a4e555"></div>
<script type="text/javascript">
  var VEGA_DEBUG = (typeof VEGA_DEBUG == "undefined") ? {} : VEGA_DEBUG;
  (function(spec, embedOpt){
    let outputDiv = document.currentScript.previousElementSibling;
    if (outputDiv.id !== "altair-viz-68067fa3f2094a61bdc29adf78a4e555") {
      outputDiv = document.getElementById("altair-viz-68067fa3f2094a61bdc29adf78a4e555");
    }
    const paths = {
      "vega": "https://cdn.jsdelivr.net/npm/vega@5?noext",
      "vega-lib": "https://cdn.jsdelivr.net/npm/vega-lib?noext",
      "vega-lite": "https://cdn.jsdelivr.net/npm/vega-lite@5.20.1?noext",
      "vega-embed": "https://cdn.jsdelivr.net/npm/vega-embed@6?noext",
    };

    function maybeLoadScript(lib, version) {
      var key = `${lib.replace("-", "")}_version`;
      return (VEGA_DEBUG[key] == version) ?
        Promise.resolve(paths[lib]) :
        new Promise(function(resolve, reject) {
          var s = document.createElement('script');
          document.getElementsByTagName("head")[0].appendChild(s);
          s.async = true;
          s.onload = () => {
            VEGA_DEBUG[key] = version;
            return resolve(paths[lib]);
          };
          s.onerror = () => reject(`Error loading script: ${paths[lib]}`);
          s.src = paths[lib];
        });
    }

    function showError(err) {
      outputDiv.innerHTML = `<div class="error" style="color:red;">${err}</div>`;
      throw err;
    }

    function displayChart(vegaEmbed) {
      vegaEmbed(outputDiv, spec, embedOpt)
        .catch(err => showError(`Javascript Error: ${err.message}<br>This usually means there's a typo in your chart specification. See the javascript console for the full traceback.`));
    }

    if(typeof define === "function" && define.amd) {
      requirejs.config({paths});
      require(["vega-embed"], displayChart, err => showError(`Error loading script: ${err.message}`));
    } else {
      maybeLoadScript("vega", "5")
        .then(() => maybeLoadScript("vega-lite", "5.20.1"))
        .then(() => maybeLoadScript("vega-embed", "6"))
        .catch(showError)
        .then(() => displayChart(vegaEmbed));
    }
  })({"config": {"view": {"continuousWidth": 300, "continuousHeight": 300}}, "layer": [{"mark": {"type": "bar", "color": "seagreen"}, "encoding": {"x": {"field": "Year", "title": "Year", "type": "ordinal"}, "y": {"field": "UniqueCount", "title": "Number of Unique Short-Term Hospitals", "type": "quantitative"}}, "title": "Number of Unique Short-Term Hospitals in Dataset by Year"}, {"mark": {"type": "text", "align": "center", "baseline": "bottom", "dy": -5}, "encoding": {"text": {"field": "UniqueCount", "type": "quantitative"}, "x": {"field": "Year", "title": "Year", "type": "ordinal"}, "y": {"field": "UniqueCount", "title": "Number of Unique Short-Term Hospitals", "type": "quantitative"}}, "title": "Number of Unique Short-Term Hospitals in Dataset by Year"}], "data": {"name": "data-191093a5d9b5bbecb1add298ce58fc15"}, "height": 300, "width": 400, "$schema": "https://vega.github.io/schema/vega-lite/v5.20.1.json", "datasets": {"data-191093a5d9b5bbecb1add298ce58fc15": [{"Year": 2016, "UniqueCount": 7245}, {"Year": 2017, "UniqueCount": 7260}, {"Year": 2018, "UniqueCount": 7277}, {"Year": 2019, "UniqueCount": 7303}]}}, {"mode": "vega-lite"});
</script>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>2016 Duplicates: 0
2017 Duplicates: 0
2018 Duplicates: 0
2019 Duplicates: 0</code></pre>
</div>
</div>
<pre><code>b.</code></pre>
<p>The identical values in both plots indicate that each short-term hospital appears only once per year, with no duplicates. This structure confirms that each hospital’s CMS certification number is unique annually, allowing for clear year-over-year tracking.</p>
</section>
<section id="identify-hospital-closures-in-pos-file-15-pts" class="level2">
<h2 class="anchored" data-anchor-id="identify-hospital-closures-in-pos-file-15-pts">Identify hospital closures in POS file (15 pts) (*)</h2>
<ol type="1">
<li></li>
</ol>
<div id="67073b1e" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Filter active hospitals in each year</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>active_2016 <span class="op">=</span> data_2016[data_2016[<span class="st">'PGM_TRMNTN_CD'</span>] <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>active_2017 <span class="op">=</span> data_2017[data_2017[<span class="st">'PGM_TRMNTN_CD'</span>] <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>active_2018 <span class="op">=</span> data_2018[data_2018[<span class="st">'PGM_TRMNTN_CD'</span>] <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>active_2019 <span class="op">=</span> data_2019[data_2019[<span class="st">'PGM_TRMNTN_CD'</span>] <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Define function to check if provider is active in a given year</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> provider_in_year(df, provider_num):</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    row <span class="op">=</span> df[df[<span class="st">'PRVDR_NUM'</span>] <span class="op">==</span> provider_num]</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="kw">not</span> row.empty <span class="kw">and</span> row[<span class="st">'PGM_TRMNTN_CD'</span>].values[<span class="dv">0</span>] <span class="op">==</span> <span class="dv">0</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Determine closure year for each provider number</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> determine_closure_year(provider_num):</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> provider_in_year(active_2017, provider_num):</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="dv">2017</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> <span class="kw">not</span> provider_in_year(active_2018, provider_num):</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="dv">2018</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> <span class="kw">not</span> provider_in_year(active_2019, provider_num):</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="dv">2019</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="va">None</span></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Apply closure detection on active hospitals in 2016</span></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>active_2016_only <span class="op">=</span> active_2016[active_2016[<span class="st">'PGM_TRMNTN_CD'</span>] <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>active_2016_only[<span class="st">'Year_Closed'</span>] <span class="op">=</span> active_2016_only[<span class="st">'PRVDR_NUM'</span>].<span class="bu">apply</span>(determine_closure_year)</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: Filter out hospitals that have a closure year assigned</span></span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>closed_hospitals <span class="op">=</span> active_2016_only.dropna(subset<span class="op">=</span>[<span class="st">'Year_Closed'</span>]).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Output the result</span></span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Number of suspected hospital closures: </span><span class="sc">{</span><span class="bu">len</span>(closed_hospitals)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>closed_hospitals[[<span class="st">'FAC_NAME'</span>, <span class="st">'ZIP_CD'</span>, <span class="st">'Year_Closed'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of suspected hospital closures: 174</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">FAC_NAME</th>
<th data-quarto-table-cell-role="th">ZIP_CD</th>
<th data-quarto-table-cell-role="th">Year_Closed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>WEDOWEE HOSPITAL</td>
<td>36278.0</td>
<td>2019.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>GEORGIANA MEDICAL CENTER</td>
<td>36033.0</td>
<td>2019.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>RMC JACKSONVILLE</td>
<td>36265.0</td>
<td>2018.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>NORTH ALABAMA SPECIALITY HOSPITAL</td>
<td>35611.0</td>
<td>2018.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>ABRAZO MARYVALE CAMPUS</td>
<td>85031.0</td>
<td>2017.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">169</td>
<td>LITTLE RIVER HEALTHCARE CAMERON HOSPITAL</td>
<td>76520.0</td>
<td>2019.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">170</td>
<td>BAY AREA REGIONAL MEDICAL CENTER, LLC</td>
<td>77598.0</td>
<td>2018.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">171</td>
<td>BAYLOR EMERGENCY MEDICAL CENTER</td>
<td>75087.0</td>
<td>2019.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">172</td>
<td>CONTINUECARE HOSPITAL AT MEDICAL CENTER ODESSA</td>
<td>79761.0</td>
<td>2017.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">173</td>
<td>TEXAS GENERAL HOSPITAL- VZRMC LP</td>
<td>75140.0</td>
<td>2019.0</td>
</tr>
</tbody>
</table>

<p>174 rows × 3 columns</p>
</div>
</div>
</div>
<ol start="2" type="1">
<li></li>
</ol>
<div id="55a2efa8" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort the closed hospitals by facility name</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>sorted_closed_hospitals <span class="op">=</span> closed_hospitals.sort_values(by<span class="op">=</span><span class="st">'FAC_NAME'</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the names and year of suspected closure for the first 10 rows</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>sorted_closed_hospitals[[<span class="st">'FAC_NAME'</span>, <span class="st">'Year_Closed'</span>]].head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">FAC_NAME</th>
<th data-quarto-table-cell-role="th">Year_Closed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>ABRAZO MARYVALE CAMPUS</td>
<td>2017.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>ADVENTIST MEDICAL CENTER - CENTRAL VALLEY</td>
<td>2017.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>AFFINITY MEDICAL CENTER</td>
<td>2018.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>ALBANY MEDICAL CENTER / SOUTH CLINICAL CAMPUS</td>
<td>2017.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>ALLEGIANCE SPECIALTY HOSPITAL OF KILGORE</td>
<td>2017.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>ALLIANCE LAIRD HOSPITAL</td>
<td>2019.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>ALLIANCEHEALTH DEACONESS</td>
<td>2019.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>ANNE BATES LEACH EYE HOSPITAL</td>
<td>2019.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>ARKANSAS VALLEY REGIONAL MEDICAL CENTER</td>
<td>2017.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>BANNER CHURCHILL COMMUNITY HOSPITAL</td>
<td>2017.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<ol start="3" type="1">
<li><ol type="a">
<li></li>
</ol></li>
</ol>
<div id="cbaba96e" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Count active hospitals by ZIP code for each year</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>active_by_zip_2016 <span class="op">=</span> active_2016[<span class="st">'ZIP_CD'</span>].value_counts().to_dict()</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>active_by_zip_2017 <span class="op">=</span> active_2017[<span class="st">'ZIP_CD'</span>].value_counts().to_dict()</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>active_by_zip_2018 <span class="op">=</span> active_2018[<span class="st">'ZIP_CD'</span>].value_counts().to_dict()</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>active_by_zip_2019 <span class="op">=</span> active_2019[<span class="st">'ZIP_CD'</span>].value_counts().to_dict()</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Function to check if closure might be due to merger/acquisition</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> is_possible_merger(row):</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    zip_code <span class="op">=</span> row[<span class="st">'ZIP_CD'</span>]</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    year_closed <span class="op">=</span> row[<span class="st">'Year_Closed'</span>]</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> year_closed <span class="op">==</span> <span class="dv">2017</span>:</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> active_by_zip_2016.get(zip_code, <span class="dv">0</span>) <span class="op">&lt;=</span> active_by_zip_2017.get(zip_code, <span class="dv">0</span>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> year_closed <span class="op">==</span> <span class="dv">2018</span>:</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> active_by_zip_2017.get(zip_code, <span class="dv">0</span>) <span class="op">&lt;=</span> active_by_zip_2018.get(zip_code, <span class="dv">0</span>)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> year_closed <span class="op">==</span> <span class="dv">2019</span>:</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> active_by_zip_2018.get(zip_code, <span class="dv">0</span>) <span class="op">&lt;=</span> active_by_zip_2019.get(zip_code, <span class="dv">0</span>)</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="va">False</span></span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Apply the function to identify potential mergers/acquisitions</span></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>closed_hospitals[<span class="st">'Possible_Merger'</span>] <span class="op">=</span> closed_hospitals.<span class="bu">apply</span>(is_possible_merger, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the suspected closures that might be due to a merger/acquisition</span></span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>potential_mergers <span class="op">=</span> closed_hospitals[closed_hospitals[<span class="st">'Possible_Merger'</span>]]</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Output the result</span></span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>num_potential_mergers <span class="op">=</span> <span class="bu">len</span>(potential_mergers)</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Number of suspected hospital closures that fit the merger/acquisition definition: </span><span class="sc">{</span>num_potential_mergers<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of suspected hospital closures that fit the merger/acquisition definition: 8</code></pre>
</div>
</div>
<pre><code>b.</code></pre>
<div id="ae495675" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the corrected number of closures after removing mergers/acquisitions</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>corrected_closures <span class="op">=</span> <span class="bu">len</span>(closed_hospitals) <span class="op">-</span> num_potential_mergers</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Number of hospitals remaining after correcting for mergers/acquisitions: </span><span class="sc">{</span>corrected_closures<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of hospitals remaining after correcting for mergers/acquisitions: 166</code></pre>
</div>
</div>
<pre><code>c.</code></pre>
<div id="4a520802" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter out the potential mergers/acquisitions to get the corrected closures</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>corrected_closures <span class="op">=</span> closed_hospitals[<span class="op">~</span>closed_hospitals[<span class="st">'Possible_Merger'</span>]]</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort the corrected closures by facility name</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>sorted_corrected_closures <span class="op">=</span> corrected_closures.sort_values(by<span class="op">=</span><span class="st">'FAC_NAME'</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first 10 rows</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>sorted_corrected_closures[[<span class="st">'FAC_NAME'</span>, <span class="st">'ZIP_CD'</span>, <span class="st">'Year_Closed'</span>]].head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">FAC_NAME</th>
<th data-quarto-table-cell-role="th">ZIP_CD</th>
<th data-quarto-table-cell-role="th">Year_Closed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>ABRAZO MARYVALE CAMPUS</td>
<td>85031.0</td>
<td>2017.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">10</td>
<td>ADVENTIST MEDICAL CENTER - CENTRAL VALLEY</td>
<td>93230.0</td>
<td>2017.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">97</td>
<td>AFFINITY MEDICAL CENTER</td>
<td>44646.0</td>
<td>2018.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">80</td>
<td>ALBANY MEDICAL CENTER / SOUTH CLINICAL CAMPUS</td>
<td>12208.0</td>
<td>2017.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">140</td>
<td>ALLEGIANCE SPECIALTY HOSPITAL OF KILGORE</td>
<td>75662.0</td>
<td>2017.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">62</td>
<td>ALLIANCE LAIRD HOSPITAL</td>
<td>39365.0</td>
<td>2019.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">101</td>
<td>ALLIANCEHEALTH DEACONESS</td>
<td>73112.0</td>
<td>2019.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">26</td>
<td>ANNE BATES LEACH EYE HOSPITAL</td>
<td>33136.0</td>
<td>2019.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">21</td>
<td>ARKANSAS VALLEY REGIONAL MEDICAL CENTER</td>
<td>81050.0</td>
<td>2017.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">69</td>
<td>BANNER CHURCHILL COMMUNITY HOSPITAL</td>
<td>89406.0</td>
<td>2017.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="download-census-zip-code-shapefile-10-pt" class="level2">
<h2 class="anchored" data-anchor-id="download-census-zip-code-shapefile-10-pt">Download Census zip code shapefile (10 pt)</h2>
<ol type="1">
<li><ol type="a">
<li></li>
</ol></li>
</ol>
<p>.shp: Main file with geometric shapes of features. .shx: Index file for quick access to shapes. .dbf: Attribute data in table format. .prj: Projection information for the coordinate system. .xml: Metadata about the dataset.</p>
<pre><code>b. </code></pre>
<div id="d9f26afd" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace 'shapefile_directory' with the path to your extracted shapefile directory</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>shapefile_directory <span class="op">=</span> <span class="st">"/Users/attaullah/Documents/problem-set-4-atta/gz_2010_us_860_00_500k"</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Get a list of files and their sizes</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> file_name <span class="kw">in</span> os.listdir(shapefile_directory):</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    file_path <span class="op">=</span> os.path.join(shapefile_directory, file_name)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    size_mb <span class="op">=</span> os.path.getsize(file_path) <span class="op">/</span> (<span class="dv">1024</span> <span class="op">*</span> <span class="dv">1024</span>)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>file_name<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>size_mb<span class="sc">:.2f}</span><span class="ss"> MB"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>gz_2010_us_860_00_500k.prj: 0.00 MB
gz_2010_us_860_00_500k.shx: 0.25 MB
gz_2010_us_860_00_500k.shp: 798.74 MB
gz_2010_us_860_00_500k.dbf: 6.13 MB
gz_2010_us_860_00_500k.xml: 0.01 MB</code></pre>
</div>
</div>
<p>This provides an overview of file sizes, with .shp being the largest due to detailed geometry data.</p>
<ol start="2" type="1">
<li></li>
</ol>
<div id="07bbc61c" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load 2016 POS data and filter for short-term hospitals in Texas</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>hospital_data_path <span class="op">=</span> <span class="st">"/Users/attaullah/Documents/problem-set-4-atta/pos2016.csv"</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>pos2016 <span class="op">=</span> pd.read_csv(hospital_data_path)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>texas_hospitals <span class="op">=</span> pos2016[(pos2016[<span class="st">"PRVDR_CTGRY_SBTYP_CD"</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>                          (pos2016[<span class="st">"PRVDR_CTGRY_CD"</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>                          (pos2016[<span class="st">"ZIP_CD"</span>].astype(<span class="bu">str</span>).<span class="bu">str</span>.startswith((<span class="st">"75"</span>, <span class="st">"76"</span>, <span class="st">"77"</span>, <span class="st">"78"</span>, <span class="st">"79"</span>)))]</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardize ZIP codes as 5-digit strings</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>texas_hospitals[<span class="st">"ZIP_CD"</span>] <span class="op">=</span> texas_hospitals[<span class="st">"ZIP_CD"</span>].astype(<span class="bu">int</span>).astype(<span class="bu">str</span>).<span class="bu">str</span>.zfill(<span class="dv">5</span>)</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate number of hospitals per ZIP code in Texas</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>hospital_counts <span class="op">=</span> texas_hospitals.groupby(<span class="st">"ZIP_CD"</span>).size().reset_index(name<span class="op">=</span><span class="st">"Hospital_Count"</span>)</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Load Texas ZIP code shapefile and filter for Texas ZIPs</span></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>shapefile_path <span class="op">=</span> <span class="st">"/Users/attaullah/Documents/problem-set-4-atta/gz_2010_us_860_00_500k/gz_2010_us_860_00_500k.shp"</span></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>zip_gdf <span class="op">=</span> gpd.read_file(shapefile_path)</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>zip_gdf[<span class="st">"ZCTA5"</span>] <span class="op">=</span> zip_gdf[<span class="st">"ZCTA5"</span>].astype(<span class="bu">str</span>).<span class="bu">str</span>.zfill(<span class="dv">5</span>)</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>texas_zip_gdf <span class="op">=</span> zip_gdf[zip_gdf[<span class="st">"ZCTA5"</span>].<span class="bu">str</span>.startswith((<span class="st">"75"</span>, <span class="st">"76"</span>, <span class="st">"77"</span>, <span class="st">"78"</span>, <span class="st">"79"</span>))]</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge hospital data with Texas ZIP code shapefile</span></span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>merged_gdf <span class="op">=</span> texas_zip_gdf.merge(hospital_counts, left_on<span class="op">=</span><span class="st">"ZCTA5"</span>, right_on<span class="op">=</span><span class="st">"ZIP_CD"</span>, how<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>merged_gdf[<span class="st">"Hospital_Count"</span>] <span class="op">=</span> merged_gdf[<span class="st">"Hospital_Count"</span>].fillna(<span class="dv">0</span>)</span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the distribution of hospital counts</span></span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(merged_gdf[<span class="st">'Hospital_Count'</span>].describe())</span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(merged_gdf[<span class="st">'Hospital_Count'</span>].value_counts().head(<span class="dv">20</span>))</span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot choropleth map of hospital counts by ZIP code in Texas</span></span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>))</span>
<span id="cb23-33"><a href="#cb23-33" aria-hidden="true" tabindex="-1"></a>merged_gdf.plot(</span>
<span id="cb23-34"><a href="#cb23-34" aria-hidden="true" tabindex="-1"></a>    column<span class="op">=</span><span class="st">"Hospital_Count"</span>,</span>
<span id="cb23-35"><a href="#cb23-35" aria-hidden="true" tabindex="-1"></a>    cmap<span class="op">=</span><span class="st">"OrRd"</span>,</span>
<span id="cb23-36"><a href="#cb23-36" aria-hidden="true" tabindex="-1"></a>    linewidth<span class="op">=</span><span class="fl">0.8</span>,</span>
<span id="cb23-37"><a href="#cb23-37" aria-hidden="true" tabindex="-1"></a>    edgecolor<span class="op">=</span><span class="st">"gray"</span>,</span>
<span id="cb23-38"><a href="#cb23-38" aria-hidden="true" tabindex="-1"></a>    legend<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb23-39"><a href="#cb23-39" aria-hidden="true" tabindex="-1"></a>    legend_kwds<span class="op">=</span>{<span class="st">"label"</span>: <span class="st">"Hospital Count"</span>},</span>
<span id="cb23-40"><a href="#cb23-40" aria-hidden="true" tabindex="-1"></a>    ax<span class="op">=</span>ax</span>
<span id="cb23-41"><a href="#cb23-41" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-42"><a href="#cb23-42" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Number of Hospitals by ZIP Code in Texas (2016)"</span>, fontsize<span class="op">=</span><span class="dv">15</span>)</span>
<span id="cb23-43"><a href="#cb23-43" aria-hidden="true" tabindex="-1"></a>ax.axis(<span class="st">"off"</span>)  <span class="co"># Remove axis for cleaner map</span></span>
<span id="cb23-44"><a href="#cb23-44" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/sd/jd56rfvs19gbncmb5yqlmfym0000gn/T/ipykernel_59453/93614499.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  texas_hospitals["ZIP_CD"] = texas_hospitals["ZIP_CD"].astype(int).astype(str).str.zfill(5)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>count    1935.000000
mean        0.377778
std         0.822023
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max        10.000000
Name: Hospital_Count, dtype: float64
Hospital_Count
0.0     1445
1.0      345
2.0       93
3.0       30
4.0       12
6.0        5
5.0        3
10.0       1
7.0        1
Name: count, dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pset4_template_files/figure-html/cell-11-output-3.png" width="726" height="629" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="calculate-zip-codes-distance-to-the-nearest-hospital-20-pts" class="level2">
<h2 class="anchored" data-anchor-id="calculate-zip-codes-distance-to-the-nearest-hospital-20-pts">Calculate zip code’s distance to the nearest hospital (20 pts) (*)</h2>
<ol type="1">
<li></li>
</ol>
<div id="89bdcdac" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> shapely.geometry <span class="im">import</span> Point</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the ZIP code shapefile</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>shapefile_path <span class="op">=</span> <span class="st">'/Users/attaullah/Documents/problem-set-4-atta/gz_2010_us_860_00_500k/gz_2010_us_860_00_500k.shp'</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>zip_gdf <span class="op">=</span> gpd.read_file(shapefile_path)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the centroid for each ZIP code polygon</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming 'ZCTA5' is the ZIP code column in the shapefile</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>zip_gdf[<span class="st">'centroid'</span>] <span class="op">=</span> zip_gdf.geometry.centroid</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new GeoDataFrame with centroids</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>zips_all_centroids <span class="op">=</span> gpd.GeoDataFrame(zip_gdf[[<span class="st">'ZCTA5'</span>, <span class="st">'centroid'</span>]], geometry<span class="op">=</span><span class="st">'centroid'</span>)</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the dimensions of the resulting GeoDataFrame</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Dimensions of zips_all_centroids:"</span>, zips_all_centroids.shape)</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first few rows to understand the structure</span></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(zips_all_centroids.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/sd/jd56rfvs19gbncmb5yqlmfym0000gn/T/ipykernel_59453/4229051823.py:10: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  zip_gdf['centroid'] = zip_gdf.geometry.centroid</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Dimensions of zips_all_centroids: (33120, 2)
   ZCTA5                    centroid
0  01040  POINT (-72.64107 42.21257)
1  01050  POINT (-72.86985 42.28786)
2  01053  POINT (-72.71162 42.35349)
3  01056  POINT (-72.45805 42.19215)
4  01057   POINT (-72.3243 42.09165)</code></pre>
</div>
</div>
<p>The zips_all_centroids GeoDataFrame contains the centroids of each ZIP code area in the U.S., representing the central point of each geographic area.</p>
<p>Dimensions: (33120, 2), with 33,120 rows and 2 columns, where each row represents a ZIP code area.</p>
<p>Columns:</p>
<p>ZCTA5: ZIP Code Tabulation Area (ZIP code) as a string. centroid: Geometric POINT object with latitude and longitude, marking the center of each ZIP code area.</p>
<ol start="2" type="1">
<li></li>
</ol>
<div id="b3f8a860" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define ZIP code prefixes for Texas and its bordering states</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>texas_prefixes <span class="op">=</span> [<span class="st">"75"</span>, <span class="st">"76"</span>, <span class="st">"77"</span>, <span class="st">"78"</span>, <span class="st">"79"</span>]  <span class="co"># Texas</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>bordering_prefixes <span class="op">=</span> texas_prefixes <span class="op">+</span> [</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"73"</span>, <span class="st">"74"</span>,              <span class="co"># Oklahoma</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"870"</span>, <span class="st">"871"</span>, <span class="st">"872"</span>, <span class="st">"873"</span>, <span class="st">"874"</span>, <span class="st">"875"</span>, <span class="st">"876"</span>, <span class="st">"877"</span>, <span class="st">"878"</span>, <span class="st">"879"</span>, <span class="st">"880"</span>, <span class="st">"881"</span>, <span class="st">"882"</span>, <span class="st">"883"</span>, <span class="st">"884"</span>,  <span class="co"># New Mexico</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"700"</span>, <span class="st">"701"</span>, <span class="st">"702"</span>, <span class="st">"703"</span>, <span class="st">"704"</span>, <span class="st">"705"</span>, <span class="st">"706"</span>, <span class="st">"707"</span>, <span class="st">"708"</span>, <span class="st">"709"</span>, <span class="st">"710"</span>, <span class="st">"711"</span>, <span class="st">"712"</span>, <span class="st">"713"</span>, <span class="st">"714"</span>, <span class="st">"715"</span>,  <span class="co"># Louisiana</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"716"</span>, <span class="st">"717"</span>, <span class="st">"718"</span>, <span class="st">"719"</span>, <span class="st">"720"</span>, <span class="st">"721"</span>, <span class="st">"722"</span>, <span class="st">"723"</span>, <span class="st">"724"</span>, <span class="st">"725"</span>, <span class="st">"726"</span>, <span class="st">"727"</span>, <span class="st">"728"</span>, <span class="st">"729"</span>  <span class="co"># Arkansas</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Create subset for Texas ZIP codes</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>zips_texas_centroids <span class="op">=</span> zips_all_centroids[zips_all_centroids[<span class="st">"ZCTA5"</span>].<span class="bu">str</span>.startswith(<span class="bu">tuple</span>(texas_prefixes))]</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Create subset for Texas and bordering states ZIP codes</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>zips_texas_borderstates_centroids <span class="op">=</span> zips_all_centroids[zips_all_centroids[<span class="st">"ZCTA5"</span>].<span class="bu">str</span>.startswith(<span class="bu">tuple</span>(bordering_prefixes))]</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number of unique ZIP codes in each subset</span></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>unique_texas_zips <span class="op">=</span> zips_texas_centroids[<span class="st">"ZCTA5"</span>].nunique()</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>unique_borderstates_zips <span class="op">=</span> zips_texas_borderstates_centroids[<span class="st">"ZCTA5"</span>].nunique()</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the results</span></span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Number of unique ZIP codes in Texas:"</span>, unique_texas_zips)</span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Number of unique ZIP codes in Texas and bordering states:"</span>, unique_borderstates_zips)</span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first few rows of each subset to verify</span></span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Sample of Texas ZIP codes:</span><span class="ch">\n</span><span class="st">"</span>, zips_texas_centroids.head())</span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Sample of Texas and bordering states ZIP codes:</span><span class="ch">\n</span><span class="st">"</span>, zips_texas_borderstates_centroids.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of unique ZIP codes in Texas: 1935
Number of unique ZIP codes in Texas and bordering states: 4057
Sample of Texas ZIP codes:
       ZCTA5                    centroid
9207  78624   POINT (-98.87707 30.2816)
9208  78626  POINT (-97.59733 30.66535)
9209  78628  POINT (-97.75112 30.64108)
9210  78631  POINT (-99.30528 30.33772)
9211  78632  POINT (-97.47045 29.69633)
Sample of Texas and bordering states ZIP codes:
       ZCTA5                    centroid
8870  70003  POINT (-90.21397 29.99864)
8871  70030  POINT (-90.43225 29.81731)
8872  70032  POINT (-89.99779 29.95816)
8873  70036  POINT (-90.12115 29.70903)
8874  70038  POINT (-89.39875 29.32533)</code></pre>
</div>
</div>
<p>The output shows: Number of unique ZIP codes in Texas: 1935 Number of unique ZIP codes in Texas and bordering states: 4057</p>
<ol start="3" type="1">
<li></li>
</ol>
<div id="10b92dc8" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Assume we already have `zips_texas_borderstates_centroids` created and `hospital_counts` data from the previous part.</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter hospital data to include only ZIP codes with at least one hospital in 2016</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 'hospital_counts' should be the dataframe that contains ZIP codes and counts of hospitals in each ZIP code</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>hospital_counts_2016 <span class="op">=</span> hospital_counts[hospital_counts[<span class="st">'Hospital_Count'</span>] <span class="op">&gt;</span> <span class="dv">0</span>]</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform an inner merge on 'ZCTA5' (ZIP code) to get only those ZIP codes with at least one hospital</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>zips_withhospital_centroids <span class="op">=</span> zips_texas_borderstates_centroids.merge(</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>    hospital_counts_2016, </span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>    left_on<span class="op">=</span><span class="st">"ZCTA5"</span>, </span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>    right_on<span class="op">=</span><span class="st">"ZIP_CD"</span>, </span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>    how<span class="op">=</span><span class="st">"inner"</span></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the resulting GeoDataFrame</span></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Dimensions of zips_withhospital_centroids:"</span>, zips_withhospital_centroids.shape)</span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(zips_withhospital_centroids.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Dimensions of zips_withhospital_centroids: (490, 4)
   ZCTA5                    centroid ZIP_CD  Hospital_Count
0  78624   POINT (-98.87707 30.2816)  78624               1
1  78626  POINT (-97.59733 30.66535)  78626               1
2  78636  POINT (-98.41885 30.30504)  78636               1
3  78640  POINT (-97.82814 29.99496)  78640               1
4  78643  POINT (-98.69472 30.69029)  78643               1</code></pre>
</div>
</div>
<p>Merge Type: I used an inner join to ensure that the resulting zips_withhospital_centroids GeoDataFrame only includes ZIP codes that have at least one hospital in 2016 and are also present in the zips_texas_borderstates_centroids GeoDataFrame.</p>
<p>Merge Variable: The merge is performed on the ZCTA5 column from zips_texas_borderstates_centroids and ZIP_CD from hospital_counts_2016, which represent ZIP codes in both datasets.</p>
<ol start="4" type="1">
<li><ol type="a">
<li></li>
</ol></li>
</ol>
<div id="8e52c957" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reproject both GeoDataFrames to a projected CRS (e.g., EPSG:5070 for USA)</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>zips_texas_centroids <span class="op">=</span> zips_texas_centroids.to_crs(epsg<span class="op">=</span><span class="dv">5070</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>zips_withhospital_centroids <span class="op">=</span> zips_withhospital_centroids.to_crs(epsg<span class="op">=</span><span class="dv">5070</span>)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-run the distance calculation with the reprojected GeoDataFrames</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset to 10 ZIP codes in Texas</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>subset_texas_centroids <span class="op">=</span> zips_texas_centroids.iloc[:<span class="dv">10</span>]</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Start timing the process</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>start_time <span class="op">=</span> time.time()</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the nearest hospital distance for each ZIP code in the subset</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>subset_texas_centroids[<span class="st">'nearest_hospital_distance'</span>] <span class="op">=</span> subset_texas_centroids[<span class="st">'centroid'</span>].<span class="bu">apply</span>(</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>    <span class="kw">lambda</span> x: zips_withhospital_centroids.distance(x).<span class="bu">min</span>()</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a><span class="co"># End timing</span></span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>end_time <span class="op">=</span> time.time()</span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>subset_time <span class="op">=</span> end_time <span class="op">-</span> start_time</span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Time taken for 10 ZIP code calculations:"</span>, subset_time, <span class="st">"seconds"</span>)</span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate time for full calculation</span></span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a>estimated_total_time <span class="op">=</span> subset_time <span class="op">*</span> (<span class="bu">len</span>(zips_texas_centroids) <span class="op">/</span> <span class="dv">10</span>)</span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Estimated time for the full procedure:"</span>, estimated_total_time, <span class="st">"seconds"</span>)</span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the results for the subset</span></span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(subset_texas_centroids[[<span class="st">'ZCTA5'</span>, <span class="st">'nearest_hospital_distance'</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time taken for 10 ZIP code calculations: 0.005772113800048828 seconds
Estimated time for the full procedure: 1.1169040203094482 seconds
      ZCTA5  nearest_hospital_distance
9207  78624                   0.000000
9208  78626                   0.000000
9209  78628               12225.805307
9210  78631               36540.773495
9211  78632               15879.134200
9212  78633               17245.762671
9213  78634               11396.935777
9214  78635               17095.102419
9215  78636                   0.000000
9216  78638               15982.824530</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/attaullah/Library/Python/3.9/lib/python/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)</code></pre>
</div>
</div>
<pre><code>b.</code></pre>
<div id="3b70bebf" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Start the timer for the full calculation on zips_texas_centroids</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>start_time_full <span class="op">=</span> time.time()</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply the distance calculation for each ZIP code in Texas to the nearest ZIP code with a hospital</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>zips_texas_centroids[<span class="st">"nearest_hospital_distance"</span>] <span class="op">=</span> zips_texas_centroids[<span class="st">"centroid"</span>].<span class="bu">apply</span>(</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">lambda</span> x: zips_withhospital_centroids.distance(x).<span class="bu">min</span>()</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="co"># End the timer</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>end_time_full <span class="op">=</span> time.time()</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>actual_time_full <span class="op">=</span> end_time_full <span class="op">-</span> start_time_full</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Print out the actual time taken</span></span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Actual time for full calculation: </span><span class="sc">{</span>actual_time_full<span class="sc">}</span><span class="ss"> seconds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Actual time for full calculation: 0.30712890625 seconds</code></pre>
</div>
</div>
<p>The actual time of 0.31 seconds is quite close to the estimated time of 0.66 seconds, showing the estimation was reasonably accurate.</p>
<pre><code>c. </code></pre>
<p>load and read the contents of the .prj file, which provides the geographic coordinate system (GCS) details:</p>
<div id="af3d676e" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Path to the .prj file</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>prj_file_path <span class="op">=</span> <span class="st">'/Users/attaullah/Documents/problem-set-4-atta/gz_2010_us_860_00_500k/gz_2010_us_860_00_500k.prj'</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read and print the .prj file contents</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(prj_file_path, <span class="st">'r'</span>) <span class="im">as</span> <span class="bu">file</span>:</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>    prj_contents <span class="op">=</span> <span class="bu">file</span>.read()</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Contents of the .prj file:"</span>)</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(prj_contents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Contents of the .prj file:
GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137,298.257222101]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]</code></pre>
</div>
</div>
<p>Since the unit in the dataset is in degrees, I used an approximation to convert degrees to miles at a latitude of 30° (Texas’ approximate latitude). For conversions, it’s commonly estimated that 1 degree of latitude equals roughly 69 miles, while 1 degree of longitude varies based on latitude. At 30° latitude, the conversion factor for longitude is approximately 69.172 miles.</p>
<p>This conversion method is based on information provided at: https://gis.stackexchange.com/questions/142326/calculating-longitude-length-in-miles</p>
<p>Using these estimates, I applied an average of latitude and longitude conversions to calculate the distance in miles:</p>
<div id="cc0bb805" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to convert distance in degrees to miles at a given latitude (approx. for Texas)</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> degrees_to_miles(distance_in_degrees, latitude<span class="op">=</span><span class="dv">30</span>):</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Convert latitude to radians</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>    latitude_in_radians <span class="op">=</span> math.radians(latitude)</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Approximate miles per degree for latitude and longitude</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>    miles_per_degree_latitude <span class="op">=</span> <span class="fl">69.0</span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>    miles_per_degree_longitude <span class="op">=</span> <span class="fl">69.172</span> <span class="op">*</span> math.cos(latitude_in_radians)</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Average of latitude and longitude mile conversion for more accuracy</span></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>    avg_miles_per_degree <span class="op">=</span> (miles_per_degree_latitude <span class="op">+</span> miles_per_degree_longitude) <span class="op">/</span> <span class="dv">2</span></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> distance_in_degrees <span class="op">*</span> avg_miles_per_degree</span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the computed average distance in degrees from the dataset</span></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a>distance_in_degrees <span class="op">=</span> <span class="fl">0.0753484763</span>  <span class="co"># Computed average distance in degrees</span></span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a>distance_in_miles <span class="op">=</span> degrees_to_miles(distance_in_degrees)</span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Average distance to nearest hospital (in miles):"</span>, distance_in_miles)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Average distance to nearest hospital (in miles): 4.856386714209268</code></pre>
</div>
</div>
<ol start="5" type="1">
<li><ol type="a">
<li></li>
</ol></li>
</ol>
<div id="8273a60b" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the nearest hospital distance in degrees</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>zips_texas_centroids[<span class="st">"nearest_hospital_distance_degrees"</span>] <span class="op">=</span> zips_texas_centroids[<span class="st">"centroid"</span>].<span class="bu">apply</span>(</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">lambda</span> x: zips_withhospital_centroids.distance(x).<span class="bu">min</span>()</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the average distance in degrees</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>average_distance_degrees <span class="op">=</span> zips_texas_centroids[<span class="st">"nearest_hospital_distance_degrees"</span>].mean()</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Average distance to the nearest hospital for each ZIP code in Texas (in degrees):"</span>, average_distance_degrees)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Average distance to the nearest hospital for each ZIP code in Texas (in degrees): 13218.169063520218</code></pre>
</div>
</div>
<p>It is in Degrees.</p>
<pre><code>b.  </code></pre>
<div id="2f3b1aa9" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to convert degrees to miles based on approximate latitude for Texas (30 degrees)</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> degrees_to_miles(distance_in_degrees, latitude<span class="op">=</span><span class="dv">30</span>):</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>    latitude_in_radians <span class="op">=</span> math.radians(latitude)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>    miles_per_degree_latitude <span class="op">=</span> <span class="fl">69.0</span>  <span class="co"># Approximation for latitude degree</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>    miles_per_degree_longitude <span class="op">=</span> <span class="fl">69.172</span> <span class="op">*</span> math.cos(latitude_in_radians)  <span class="co"># Approximation for longitude degree</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>    avg_miles_per_degree <span class="op">=</span> (miles_per_degree_latitude <span class="op">+</span> miles_per_degree_longitude) <span class="op">/</span> <span class="dv">2</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> distance_in_degrees <span class="op">*</span> avg_miles_per_degree</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the previously calculated average distance in degrees</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>distance_in_miles <span class="op">=</span> degrees_to_miles(average_distance_degrees)</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Average distance to the nearest hospital for each ZIP code in Texas (in miles):"</span>, distance_in_miles)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Average distance to the nearest hospital for each ZIP code in Texas (in miles): 851942.1198468423</code></pre>
</div>
</div>
<div id="471dd489" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reproject to a projected CRS for accurate distance calculation</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>zips_texas_centroids <span class="op">=</span> zips_texas_centroids.to_crs(epsg<span class="op">=</span><span class="dv">3395</span>)  <span class="co"># World Mercator</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>zips_withhospital_centroids <span class="op">=</span> zips_withhospital_centroids.to_crs(epsg<span class="op">=</span><span class="dv">3395</span>)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Recalculate nearest hospital distance</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>zips_texas_centroids[<span class="st">"nearest_hospital_distance_meters"</span>] <span class="op">=</span> zips_texas_centroids[<span class="st">"centroid"</span>].<span class="bu">apply</span>(</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">lambda</span> x: zips_withhospital_centroids.distance(x).<span class="bu">min</span>()</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the distance from meters to miles</span></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>zips_texas_centroids[<span class="st">"nearest_hospital_distance_miles"</span>] <span class="op">=</span> zips_texas_centroids[<span class="st">"nearest_hospital_distance_meters"</span>] <span class="op">/</span> <span class="fl">1609.34</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the average distance in miles</span></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>average_distance_miles_corrected <span class="op">=</span> zips_texas_centroids[<span class="st">"nearest_hospital_distance_miles"</span>].mean()</span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Corrected average distance to nearest hospital (in miles):"</span>, average_distance_miles_corrected)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Corrected average distance to nearest hospital (in miles): 9.608947063385544</code></pre>
</div>
</div>
<p>The initial result of 996,695.26 miles for the average distance to the nearest hospital was clearly unrealistic. This suggested an issue with unit conversion.</p>
<p>After re-projecting the data for accurate distance measurements, the corrected average was 9.61 miles, which aligns well with realistic hospital distribution in Texas. This correction provided a reasonable and accurate measure of the average distance to the nearest hospital.</p>
<pre><code>c.</code></pre>
<div id="5922931d" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the choropleth map for average distance to nearest hospital in Texas</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">10</span>))</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>zips_texas_centroids.plot(</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>    column<span class="op">=</span><span class="st">'nearest_hospital_distance_miles'</span>,  <span class="co"># Column with the distance in miles</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>    cmap<span class="op">=</span><span class="st">'viridis'</span>,                            <span class="co"># Color map</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>    linewidth<span class="op">=</span><span class="fl">0.8</span>,                             <span class="co"># Border width for ZIP code polygons</span></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>    ax<span class="op">=</span>ax,</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>    edgecolor<span class="op">=</span><span class="st">'0.8'</span>,                           <span class="co"># Color for polygon borders</span></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>    legend<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>    legend_kwds<span class="op">=</span>{<span class="st">'label'</span>: <span class="st">"Distance to Nearest Hospital (miles)"</span>}</span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding map title and turning off axis for clarity</span></span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Average Distance to Nearest Hospital by ZIP Code in Texas"</span>, fontsize<span class="op">=</span><span class="dv">15</span>)</span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a>ax.axis(<span class="st">'off'</span>)  <span class="co"># Hides the axis</span></span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-19"><a href="#cb52-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the plot</span></span>
<span id="cb52-20"><a href="#cb52-20" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pset4_template_files/figure-html/cell-22-output-1.png" width="733" height="766" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="effects-of-closures-on-access-in-texas-15-pts" class="level2">
<h2 class="anchored" data-anchor-id="effects-of-closures-on-access-in-texas-15-pts">Effects of closures on access in Texas (15 pts)</h2>
<ol type="1">
<li></li>
</ol>
<div id="6105400e" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert ZIP_CD to string, remove any '.0' suffix if present, then ensure it's a 5-digit string</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>closed_hospitals[<span class="st">'ZIP_CD'</span>] <span class="op">=</span> closed_hospitals[<span class="st">'ZIP_CD'</span>].astype(<span class="bu">str</span>).<span class="bu">str</span>.replace(<span class="vs">r'\.0$'</span>, <span class="st">''</span>, regex<span class="op">=</span><span class="va">True</span>).<span class="bu">str</span>.zfill(<span class="dv">5</span>)</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the closures data for ZIP codes in Texas (based on known Texas ZIP code prefixes)</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>texas_closures <span class="op">=</span> closed_hospitals[closed_hospitals[<span class="st">'ZIP_CD'</span>].<span class="bu">str</span>.startswith((<span class="st">'75'</span>, <span class="st">'76'</span>, <span class="st">'77'</span>, <span class="st">'78'</span>, <span class="st">'79'</span>))]</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Group by ZIP code and count closures</span></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>closures_by_zipcode <span class="op">=</span> texas_closures.groupby(<span class="st">'ZIP_CD'</span>).size().reset_index(name<span class="op">=</span><span class="st">'Closure_Count'</span>)</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the table of closures by ZIP code</span></span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Table of Hospital Closures by ZIP Code in Texas (2016-2019):"</span>)</span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(closures_by_zipcode)</span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Optionally display the top affected ZIP codes for brevity</span></span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Top Affected ZIP Codes by Hospital Closures:"</span>)</span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(closures_by_zipcode.sort_values(by<span class="op">=</span><span class="st">'Closure_Count'</span>, ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Table of Hospital Closures by ZIP Code in Texas (2016-2019):
   ZIP_CD  Closure_Count
0   75042              1
1   75051              1
2   75087              1
3   75140              1
4   75231              1
5   75235              1
6   75390              1
7   75601              1
8   75662              1
9   75835              1
10  75862              1
11  76502              1
12  76520              1
13  76531              1
14  76645              1
15  77035              1
16  77054              1
17  77065              1
18  77429              1
19  77479              1
20  77598              1
21  78017              1
22  78061              1
23  78336              1
24  78613              1
25  78734              1
26  78834              1
27  79520              1
28  79529              1
29  79553              1
30  79735              1
31  79761              1
32  79902              1
Top Affected ZIP Codes by Hospital Closures:
   ZIP_CD  Closure_Count
0   75042              1
17  77065              1
31  79761              1
30  79735              1
29  79553              1
28  79529              1
27  79520              1
26  78834              1
25  78734              1
24  78613              1</code></pre>
</div>
</div>
<ol start="2" type="1">
<li></li>
</ol>
<div id="e762e811" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load Texas ZIP codes shapefile and hospital closures data</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>shapefile_path <span class="op">=</span> <span class="st">"/Users/attaullah/Documents/problem-set-4-atta/gz_2010_us_860_00_500k/gz_2010_us_860_00_500k.shp"</span>  <span class="co"># Adjust the path</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>zip_gdf <span class="op">=</span> gpd.read_file(shapefile_path)</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Define Texas ZIP code prefixes and filter the data</span></span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>texas_zip_prefixes <span class="op">=</span> [<span class="st">"75"</span>, <span class="st">"76"</span>, <span class="st">"77"</span>, <span class="st">"78"</span>, <span class="st">"79"</span>]</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>zip_gdf[<span class="st">"ZCTA5"</span>] <span class="op">=</span> zip_gdf[<span class="st">"ZCTA5"</span>].astype(<span class="bu">str</span>)</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>texas_zip_gdf <span class="op">=</span> zip_gdf[zip_gdf[<span class="st">"ZCTA5"</span>].<span class="bu">str</span>.startswith(<span class="bu">tuple</span>(texas_zip_prefixes))]</span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge Texas ZIP codes with closure data</span></span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a>closures_by_zipcode[<span class="st">'ZIP_CD'</span>] <span class="op">=</span> closures_by_zipcode[<span class="st">'ZIP_CD'</span>].astype(<span class="bu">str</span>).<span class="bu">str</span>.zfill(<span class="dv">5</span>)</span>
<span id="cb55-15"><a href="#cb55-15" aria-hidden="true" tabindex="-1"></a>texas_closure_geo <span class="op">=</span> texas_zip_gdf.merge(closures_by_zipcode, left_on<span class="op">=</span><span class="st">"ZCTA5"</span>, right_on<span class="op">=</span><span class="st">"ZIP_CD"</span>, how<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb55-16"><a href="#cb55-16" aria-hidden="true" tabindex="-1"></a>texas_closure_geo[<span class="st">'Closure_Count'</span>] <span class="op">=</span> texas_closure_geo[<span class="st">'Closure_Count'</span>].fillna(<span class="dv">0</span>)</span>
<span id="cb55-17"><a href="#cb55-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-18"><a href="#cb55-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the map</span></span>
<span id="cb55-19"><a href="#cb55-19" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>))</span>
<span id="cb55-20"><a href="#cb55-20" aria-hidden="true" tabindex="-1"></a>texas_closure_geo.plot(</span>
<span id="cb55-21"><a href="#cb55-21" aria-hidden="true" tabindex="-1"></a>    column<span class="op">=</span><span class="st">'Closure_Count'</span>,</span>
<span id="cb55-22"><a href="#cb55-22" aria-hidden="true" tabindex="-1"></a>    cmap<span class="op">=</span><span class="st">'OrRd'</span>,</span>
<span id="cb55-23"><a href="#cb55-23" aria-hidden="true" tabindex="-1"></a>    linewidth<span class="op">=</span><span class="fl">0.8</span>,</span>
<span id="cb55-24"><a href="#cb55-24" aria-hidden="true" tabindex="-1"></a>    ax<span class="op">=</span>ax,</span>
<span id="cb55-25"><a href="#cb55-25" aria-hidden="true" tabindex="-1"></a>    edgecolor<span class="op">=</span><span class="st">'0.8'</span>,</span>
<span id="cb55-26"><a href="#cb55-26" aria-hidden="true" tabindex="-1"></a>    legend<span class="op">=</span><span class="va">True</span></span>
<span id="cb55-27"><a href="#cb55-27" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb55-28"><a href="#cb55-28" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Texas ZIP Codes Directly Affected by Hospital Closures (2016-2019)"</span>)</span>
<span id="cb55-29"><a href="#cb55-29" aria-hidden="true" tabindex="-1"></a>ax.set_axis_off()</span>
<span id="cb55-30"><a href="#cb55-30" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pset4_template_files/figure-html/cell-24-output-1.png" width="712" height="625" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<ol start="3" type="1">
<li></li>
</ol>
<div id="7e2486e4" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-project to a projected CRS for accurate buffering</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>texas_zip_gdf <span class="op">=</span> texas_zip_gdf.to_crs(epsg<span class="op">=</span><span class="dv">3395</span>)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>directly_affected_zips <span class="op">=</span> texas_closure_geo[texas_closure_geo[<span class="st">'Closure_Count'</span>] <span class="op">&gt;</span> <span class="dv">0</span>].to_crs(epsg<span class="op">=</span><span class="dv">3395</span>)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Create a 10-mile buffer around directly affected ZIP codes (10 miles ≈ 16093.4 meters)</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>directly_affected_zips[<span class="st">'buffer'</span>] <span class="op">=</span> directly_affected_zips.geometry.<span class="bu">buffer</span>(<span class="fl">16093.4</span>)  <span class="co"># Buffer in meters</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Convert buffered areas to a new GeoDataFrame</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>buffered_zips <span class="op">=</span> gpd.GeoDataFrame(directly_affected_zips[[<span class="st">'ZIP_CD'</span>, <span class="st">'buffer'</span>]], geometry<span class="op">=</span><span class="st">'buffer'</span>, crs<span class="op">=</span>directly_affected_zips.crs)</span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Plot Texas ZIP codes and buffer zones for verification (optional visualization)</span></span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> texas_zip_gdf.plot(color<span class="op">=</span><span class="st">'lightgrey'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>))</span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a>buffered_zips.plot(ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">'none'</span>, edgecolor<span class="op">=</span><span class="st">'red'</span>)  <span class="co"># Buffer zones in red outline</span></span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Texas ZIP Codes and 10-Mile Buffers Around Directly Affected ZIP Codes"</span>)</span>
<span id="cb56-15"><a href="#cb56-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb56-16"><a href="#cb56-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-17"><a href="#cb56-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Perform spatial join to identify indirectly affected ZIP codes within buffer areas</span></span>
<span id="cb56-18"><a href="#cb56-18" aria-hidden="true" tabindex="-1"></a>indirectly_affected_zips <span class="op">=</span> gpd.sjoin(texas_zip_gdf, buffered_zips, how<span class="op">=</span><span class="st">'inner'</span>, predicate<span class="op">=</span><span class="st">'intersects'</span>)</span>
<span id="cb56-19"><a href="#cb56-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-20"><a href="#cb56-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: Count unique ZIP codes in the indirectly affected set</span></span>
<span id="cb56-21"><a href="#cb56-21" aria-hidden="true" tabindex="-1"></a>indirectly_affected_count <span class="op">=</span> indirectly_affected_zips[<span class="st">'ZIP_CD'</span>].nunique()</span>
<span id="cb56-22"><a href="#cb56-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Number of indirectly affected ZIP codes:"</span>, indirectly_affected_count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pset4_template_files/figure-html/cell-25-output-1.png" width="676" height="670" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of indirectly affected ZIP codes: 33</code></pre>
</div>
</div>
<ol start="4" type="1">
<li></li>
</ol>
<div id="9aa90887" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Re-project data for accuracy (if not already done)</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>texas_zip_gdf <span class="op">=</span> texas_zip_gdf.to_crs(epsg<span class="op">=</span><span class="dv">3395</span>)</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>directly_affected_zips <span class="op">=</span> texas_closure_geo[texas_closure_geo[<span class="st">'Closure_Count'</span>] <span class="op">&gt;</span> <span class="dv">0</span>].to_crs(epsg<span class="op">=</span><span class="dv">3395</span>)</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Create a 10-mile buffer around directly affected ZIP codes</span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>directly_affected_zips[<span class="st">'buffer'</span>] <span class="op">=</span> directly_affected_zips.geometry.<span class="bu">buffer</span>(<span class="fl">16093.4</span>)  <span class="co"># Buffer in meters</span></span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>buffered_zips <span class="op">=</span> gpd.GeoDataFrame(directly_affected_zips[[<span class="st">'ZCTA5'</span>, <span class="st">'buffer'</span>]], geometry<span class="op">=</span><span class="st">'buffer'</span>, crs<span class="op">=</span>directly_affected_zips.crs)</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Identify indirectly affected ZIP codes</span></span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a>indirectly_affected_zips <span class="op">=</span> gpd.sjoin(texas_zip_gdf, buffered_zips, how<span class="op">=</span><span class="st">'inner'</span>, predicate<span class="op">=</span><span class="st">'intersects'</span>)</span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a>indirectly_affected_zip_codes <span class="op">=</span> indirectly_affected_zips[<span class="st">'ZCTA5_left'</span>].unique()  <span class="co"># Use 'ZCTA5_left' from join result</span></span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Classify ZIP codes into categories</span></span>
<span id="cb58-17"><a href="#cb58-17" aria-hidden="true" tabindex="-1"></a>texas_zip_gdf[<span class="st">'category'</span>] <span class="op">=</span> <span class="st">'Not Affected'</span></span>
<span id="cb58-18"><a href="#cb58-18" aria-hidden="true" tabindex="-1"></a>texas_zip_gdf.loc[texas_zip_gdf[<span class="st">'ZCTA5'</span>].isin(directly_affected_zips[<span class="st">'ZCTA5'</span>]), <span class="st">'category'</span>] <span class="op">=</span> <span class="st">'Directly Affected'</span></span>
<span id="cb58-19"><a href="#cb58-19" aria-hidden="true" tabindex="-1"></a>texas_zip_gdf.loc[(texas_zip_gdf[<span class="st">'ZCTA5'</span>].isin(indirectly_affected_zip_codes)) <span class="op">&amp;</span> </span>
<span id="cb58-20"><a href="#cb58-20" aria-hidden="true" tabindex="-1"></a>                  (<span class="op">~</span>texas_zip_gdf[<span class="st">'ZCTA5'</span>].isin(directly_affected_zips[<span class="st">'ZCTA5'</span>])), <span class="st">'category'</span>] <span class="op">=</span> <span class="st">'Indirectly Affected'</span></span>
<span id="cb58-21"><a href="#cb58-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-22"><a href="#cb58-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: Plot the choropleth</span></span>
<span id="cb58-23"><a href="#cb58-23" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">10</span>))</span>
<span id="cb58-24"><a href="#cb58-24" aria-hidden="true" tabindex="-1"></a>category_colors <span class="op">=</span> {<span class="st">'Not Affected'</span>: <span class="st">'lightgrey'</span>, <span class="st">'Directly Affected'</span>: <span class="st">'red'</span>, <span class="st">'Indirectly Affected'</span>: <span class="st">'orange'</span>}</span>
<span id="cb58-25"><a href="#cb58-25" aria-hidden="true" tabindex="-1"></a>texas_zip_gdf.plot(column<span class="op">=</span><span class="st">'category'</span>, categorical<span class="op">=</span><span class="va">True</span>, </span>
<span id="cb58-26"><a href="#cb58-26" aria-hidden="true" tabindex="-1"></a>                   legend<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span>[category_colors.get(x) <span class="cf">for</span> x <span class="kw">in</span> texas_zip_gdf[<span class="st">'category'</span>]],</span>
<span id="cb58-27"><a href="#cb58-27" aria-hidden="true" tabindex="-1"></a>                   legend_kwds<span class="op">=</span>{<span class="st">'title'</span>: <span class="st">"Impact Category"</span>}, ax<span class="op">=</span>ax, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb58-28"><a href="#cb58-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-29"><a href="#cb58-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding a title and displaying the plot</span></span>
<span id="cb58-30"><a href="#cb58-30" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Texas ZIP Codes Categorized by Impact of Hospital Closures (2016-2019)"</span>)</span>
<span id="cb58-31"><a href="#cb58-31" aria-hidden="true" tabindex="-1"></a>plt.axis(<span class="st">'off'</span>)  <span class="co"># Hide axis for a cleaner look</span></span>
<span id="cb58-32"><a href="#cb58-32" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/sd/jd56rfvs19gbncmb5yqlmfym0000gn/T/ipykernel_59453/1336876049.py:25: UserWarning: Only specify one of 'column' or 'color'. Using 'color'.
  texas_zip_gdf.plot(column='category', categorical=True,</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pset4_template_files/figure-html/cell-26-output-2.png" width="800" height="778" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="reflecting-on-the-exercise-10-pts" class="level2">
<h2 class="anchored" data-anchor-id="reflecting-on-the-exercise-10-pts">Reflecting on the exercise (10 pts)</h2>
<ol type="1">
<li>The first-pass method risks misidentifying closures because it doesn’t account for temporary closures, facility mergers, or changes in hospital IDs. This can lead to over- or under-counting affected areas. To improve, we could:</li>
</ol>
<p>Cross-reference closures with state and local health department data to verify permanent status. Track hospital utilization trends over time to differentiate between closures and service reductions. Use multiple years of data to confirm if facilities remain closed rather than reopening under new identifiers. Integrate local news reports and community health resources to validate closures. These steps could make the identification process more accurate and reduce misclassification.</p>
<ol start="2" type="1">
<li></li>
</ol>
<p>The current approach, identifying affected ZIP codes based on a 10-mile radius around closures, provides a rough estimate but doesn’t fully capture changes in access. Here are some ways to improve:</p>
<p>Travel Time Analysis: Use drive time rather than straight-line distance, as actual access depends on road networks, traffic, and transportation options.</p>
<p>Population Density and Demand: Factor in population density and local demand to assess how many people are impacted within each affected ZIP code.</p>
<p>Alternative Facilities: Account for nearby hospitals or healthcare facilities that could serve as substitutes, providing a more realistic measure of lost access.</p>
<p>Demographic and Socioeconomic Factors: Include variables like age, income, and car ownership to reflect differences in accessibility and reliance on local hospitals across communities.</p>
<p>These adjustments could give a more accurate picture of how hospital closures impact healthcare access at the ZIP-code level.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>